#!/bin/bash
# Notes:
#   - Lists CN, SANs and Expiry date of certificate
#   - should've been done in python, but it was quick and dirty.


########################
# Global Constans and Vars
########################
EXIT_CODE=0
DEFAULT_PORT=443



########################
# Function definitions
########################

function print_usage {
        echo "Usage: $(basename $0) [host:port]" 2>&1
}


########################
# Main Program
########################
if [[ ${#} -eq 0 ]]; then
   print_usage
   EXIT_CODE=1
   exit ${EXIT_CODE}
fi

hostport=$1

host=$(echo $1 | awk -F":" '{ print $1 }')
port=$(echo $1 | awk -F":" '{ print $2 }')

if [ "${port}" == "" ]
then
  port=${DEFAULT_PORT}
fi

echo "Host: ${host}"
echo "Port: ${port}"
echo "--"
cert=$(true | openssl s_client -connect ${host}:${port} -showcerts 2>&1 | openssl x509 -noout -text)
cn=$(echo "${cert}" | grep "Subject: CN" | awk -F"=" '{ print $2 }' | sed -e 's/^[ \t]*//')
san=$(echo "${cert}" | grep DNS: | tr ',' '\n' | awk -F":" '{ print $2 }')
expires=$(echo "${cert}" | grep "Not After" | awk -F":" '{ print $2 ":" $3 ":" $4}' | sed -e 's/^[ \t]*//')
issuer=$(echo "${cert}" | grep "Issuer:" | sed -e 's/Issuer://' | sed -e 's/^[ \t]*//')

echo "CN: ${cn}"
echo "Issuer: ${issuer}"
echo
echo "Expires: ${expires}"
echo
echo "SAN(s):"
echo "${san}"

exit ${EXIT_CODE}
