#!/usr/bin/python3
# qrm - quay repo management

import os
import sys
import getopt
import argparse
import requests
from requests.auth import HTTPBasicAuth
import json
import getopt
import socket
import getpass

my_headers = {
 'Content-type': 'application/json'
 }


def getRepos(registry: str, public: bool):
  next_page = ""
  repositories = []

  while True:
     response = requests.get(
       'https://' + str(registry) + '/api/v1/repository?public=' + str(public) + '&last_modified=true&next_page=' + str(next_page),
        headers=my_headers
     ).json()
     repositories.append(response['repositories'])

     if "next_page" in response:
       next_page = response['next_page']
     else:
       break

  return repositories[0]

def getRepoTags(registry, repository):
  response = requests.get(
    'https://' + str(registry) + '/api/v1/repository/' + str(repository) +'?includeTags=true',
    headers=my_headers
  ).json()

  return response['tags']

def listAllRepoTags(registry):
  response = []

  for repo in getRepos(registry, True):
    alltags=""

    tags = getRepoTags(registry, repo['namespace'] + '/' + repo['name'])

    for tag in tags:
      alltags += str(tag) + ','

    alltags = alltags.strip(',')
    my_dict = {'repository': repo['namespace'] + '/' + repo['name'], 'tags': alltags }
    dict_copy = my_dict.copy()
    response.append(dict_copy)

  return response


def deleteTag(registry, repository, tag):
  response = requests.delete(
    'https://' + str(registry) + '/api/v1/repository/' + str(repository) +'/tag' + tag,
    headers=my_headers
  ).json()

  return response

def printAllTags(registry):
   alldata = listAllRepoTags(registry)
   print ('{:<60} {:<60}'.format("Repository", "Tags"))
   print ('{:<120}'.format("=" * 120))
   for repo in alldata:
     print ('{:<60} {:<60}'.format(repo['repository'], repo['tags']))


def checkRegistry(registry):
  print ("Checking Registry: {:<}...".format(registry), end=" ")
  try:
    socket.create_connection((registry, '443'), timeout=10)
    print ("[System: UP]...".format(registry), end=" ")
    try:
      response = requests.get(
        'https://' + str(registry) + '/api/v1/discovery',
        headers=my_headers
      )
      if response.status_code == 200:
        print ("[Quay: UP]".format(registry))
      else:
        print ("[Quay: DOWN]".format(registry))
        sys.exit("ERROR: Quay down or no quay on remote end")
    except Exception as err:
      sys.exit(err.__str__())

    return True
  except socket.timeout:
    print ("[Systen: DOWN]".format(registry))
    return False
  except Exception as err:
    sys.exit(err.__str__())

def main(argv):
  parser = argparse.ArgumentParser(description='Quay repository management script.', add_help=True)
  parser.add_argument('-r', '--registry', required=True, dest='registry', help='Set the registry to connect to')
  parser.add_argument('-p', '--repo', dest='repository', help='Set the repository to work on')
  parser.add_argument('-t', '--tag', dest='tag', help='Set the tag to work on')
  parser.add_argument('-a', '--action', dest='action', help='Set the script action', default="printalltags", choices=('printalltags','listtags','listrepos','deltag'))
  parser.add_argument('-s','--silent', action='store_true', help="silent mode, don't print checks")

  args = parser.parse_args()

  checkRegistry(args.registry)

  if args.action == 'printalltags':
    printAllTags(args.registry)
  if args.action == 'listtags':
    if args.repository:
      print (json.dumps(getRepoTags(args.registry, args.repository), indent=4))
    else:
      sys.exit("ERROR: repository not defined")
  if args.action == 'listrepos':
    print (json.dumps(getRepos(args.registry, True), indent=4))
  if args.action == 'deltag':
    if args.repository:
      if args.tag:
        print(json.dumps(deleteTag(args.registry, args.repository, args.tag), indent=4))
      else:
        sys.exit("ERROR: tag not defined")
    else:
      sys.exit("ERROR: repository not defined")

if __name__ == "__main__":

  # calling main function
  main(sys.argv)
